import React, { createContext, useCallback, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { api } from '../services/api';
import { useAuth } from '../hooks/useAuth';
import type { ConversationResponse, Message } from '../types';

interface ConversationItem {
  id: string;
  conversationId?: string;
  userId: string;
  title: string;
  isActive: boolean;
  messageCount: number;
  summary?: string | null;
  updatedAt?: string;
}

interface ConversationContextType {
  conversations: ConversationItem[];
  activeConversationId: string | null;
  messages: Message[];
  isLoadingConversations: boolean;
  isLoadingMessages: boolean;
  isSendingMessage: boolean;
  chatError: string | null;
  sendMessage: (text: string) => Promise<void>;
  selectConversation: (conversationId?: string) => Promise<void>;
  startNewConversation: () => void;
  refreshConversations: () => Promise<void>;
}

const defaultAssistantMessage = (): Message => ({
  id: 'assistant-welcome',
  role: 'assistant',
  content:
    "Hello! I'm Little Phoenix, your AI assistant powered by RAG. I can help you by answering questions based on your uploaded documents. How can I help you today?",
  timestamp: new Date(),
});

const mapConversationId = (conversation: ConversationResponse): string | undefined => {
  if (conversation.conversationId) {
    return conversation.conversationId;
  }

  if (conversation.messages.length > 0) {
    return conversation.messages[0].conversationId;
  }

  return undefined;
};

const mapConversationItem = (conversation: ConversationResponse, index: number): ConversationItem => {
  const conversationId = mapConversationId(conversation);
  const latestMessage = conversation.messages[conversation.messages.length - 1];

  return {
    id: conversationId ?? `${conversation.userId}-${conversation.title}-${index}`,
    conversationId,
    userId: conversation.userId,
    title: conversation.title,
    isActive: conversation.isActive,
    messageCount: conversation.messageCount,
    summary: conversation.summary,
    updatedAt: latestMessage?.updatedAt ?? latestMessage?.createdAt,
  };
};

const mapToUiMessage = (message: {
  id: string;
  role: string;
  content: string;
  createdAt?: string;
}): Message => ({
  id: message.id,
  role: message.role?.toLowerCase() === 'assistant' ? 'assistant' : 'user',
  content: message.content,
  timestamp: message.createdAt ? new Date(message.createdAt) : new Date(),
});

const normalizeConversationMessages = (mappedMessages: Message[]): Message[] => {
  if (mappedMessages.length <= 1) {
    return mappedMessages;
  }

  // Keep autogenerated assistant greeting first when present.
  const greetingIndex = mappedMessages.findIndex(
    (message) =>
      message.role === 'assistant' &&
      /little phoenix|how can i help|nice to meet you/i.test(message.content)
  );

  if (greetingIndex <= 0) {
    return mappedMessages;
  }

  const greetingMessage = mappedMessages[greetingIndex];
  const remainingMessages = mappedMessages.filter((_, index) => index !== greetingIndex);
  return [greetingMessage, ...remainingMessages];
};

export const ConversationContext = createContext<ConversationContextType | undefined>(undefined);

export const ConversationProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const { isAuthenticated } = useAuth();
  const [conversations, setConversations] = useState<ConversationItem[]>([]);
  const [activeConversationId, setActiveConversationId] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([defaultAssistantMessage()]);
  const [isLoadingConversations, setIsLoadingConversations] = useState(false);
  const [isLoadingMessages, setIsLoadingMessages] = useState(false);
  const [isSendingMessage, setIsSendingMessage] = useState(false);
  const [chatError, setChatError] = useState<string | null>(null);

  const fetchConversations = useCallback(async (): Promise<ConversationItem[]> => {
    const data = await api.getUserConversations();
    const mapped = data
      .map((conversation, index) => mapConversationItem(conversation, index))
      .sort((a, b) => new Date(b.updatedAt ?? 0).getTime() - new Date(a.updatedAt ?? 0).getTime());
    setConversations(mapped);
    return mapped;
  }, []);

  const selectConversation = useCallback(async (conversationId?: string) => {

    try {
      setIsLoadingMessages(true);
      setChatError(null);
      const response = await api.getConversationMessages(conversationId);
      const mappedMessages = response
        .slice()
        .sort((a, b) => Number(a.order) - Number(b.order))
        .map(mapToUiMessage);
      const normalizedMessages = normalizeConversationMessages(mappedMessages);

      setActiveConversationId(conversationId ?? (response[0]?.conversationId ?? null));
      setMessages(normalizedMessages.length > 0 ? normalizedMessages : [defaultAssistantMessage()]);
    } catch (error) {
      setChatError(error instanceof Error ? error.message : 'Failed to load conversation messages');
    } finally {
      setIsLoadingMessages(false);
    }
  }, []);

  const refreshConversations = useCallback(async () => {
    if (!isAuthenticated) return;

    try {
      setIsLoadingConversations(true);
      const mapped = await fetchConversations();

      if (mapped.length === 0) {
        setActiveConversationId(null);
        setMessages([defaultAssistantMessage()]);
        return;
      }

      const activeStillExists = activeConversationId && mapped.some((conversation) => conversation.conversationId === activeConversationId);
      if (!activeStillExists) {
        const activeConversation = mapped.find((conversation) => conversation.isActive);
        if (activeConversation) {
          await selectConversation();
        } else {
          await selectConversation(mapped[0].conversationId);
        }
      }
    } catch (error) {
      setChatError(error instanceof Error ? error.message : 'Failed to load conversation history');
    } finally {
      setIsLoadingConversations(false);
    }
  }, [activeConversationId, fetchConversations, isAuthenticated, selectConversation]);

  const startNewConversation = useCallback(() => {
    setActiveConversationId(null);
    setChatError(null);
    setMessages([defaultAssistantMessage()]);
  }, []);

  const sendMessage = useCallback(
    async (text: string) => {
      const trimmedText = text.trim();
      if (!trimmedText) return;

      const optimisticUserMessage: Message = {
        id: `local-user-${Date.now()}`,
        role: 'user',
        content: trimmedText,
        timestamp: new Date(),
      };

      setMessages((prev) => [...prev, optimisticUserMessage]);
      setIsSendingMessage(true);
      setChatError(null);

      try {
        const response = await api.ask(trimmedText, activeConversationId ?? undefined);

        const assistantMessage: Message = {
          id: response.id ?? `local-assistant-${Date.now()}`,
          role: 'assistant',
          content: response.answer,
          timestamp: response.createdAt ? new Date(response.createdAt) : new Date(),
        };

        setMessages((prev) => [...prev, assistantMessage]);

        if (response.conversationId) {
          setActiveConversationId(response.conversationId);
          await refreshConversations();
          await selectConversation(response.conversationId);
        } else {
          await refreshConversations();
        }
      } catch (error) {
        setChatError(error instanceof Error ? error.message : 'Failed to get response');
      } finally {
        setIsSendingMessage(false);
      }
    },
    [activeConversationId, refreshConversations, selectConversation]
  );

  useEffect(() => {
    if (!isAuthenticated) {
      setConversations([]);
      setActiveConversationId(null);
      setMessages([defaultAssistantMessage()]);
      setChatError(null);
      return;
    }

    refreshConversations();
  }, [isAuthenticated, refreshConversations]);

  const value = useMemo(
    () => ({
      conversations,
      activeConversationId,
      messages,
      isLoadingConversations,
      isLoadingMessages,
      isSendingMessage,
      chatError,
      sendMessage,
      selectConversation,
      startNewConversation,
      refreshConversations,
    }),
    [
      conversations,
      activeConversationId,
      messages,
      isLoadingConversations,
      isLoadingMessages,
      isSendingMessage,
      chatError,
      sendMessage,
      selectConversation,
      startNewConversation,
      refreshConversations,
    ]
  );

  return <ConversationContext.Provider value={value}>{children}</ConversationContext.Provider>;
};
