import React, { createContext, useCallback, useEffect, useRef, useMemo, useState } from 'react';
import type { ReactNode } from 'react';
import { api } from '../services/api';
import { useAuth } from '../hooks/useAuth';
import type { ConversationResponse, Message } from '../types';

interface ConversationItem {
  id: string;
  conversationId?: string;
  userId: string;
  title: string;
  isActive: boolean;
  messageCount: number;
  summary?: string | null;
  updatedAt?: string;
}

interface ConversationContextType {
  conversations: ConversationItem[];
  activeConversationId: string | null;
  messages: Message[];
  isLoadingConversations: boolean;
  isLoadingMessages: boolean;
  isSendingMessage: boolean;
  chatError: string | null;
  sendMessage: (text: string) => Promise<void>;
  selectConversation: (conversationId?: string, skipFetch?: boolean) => Promise<void>;
  startNewConversation: () => void;
  refreshConversations: () => Promise<void>;
}

const defaultAssistantMessage = (): Message => ({
  id: 'assistant-welcome',
  role: 'assistant',
  content:
    "Hello! I'm Little Phoenix, your AI assistant powered by RAG. I can help you by answering questions based on your uploaded documents. How can I help you today?",
  timestamp: new Date(),
});

const mapConversationId = (conversation: ConversationResponse): string | undefined => {
  // First check if 'id' is present (primary backend field)
  if (conversation.id) {
    return conversation.id;
  }

  // Check if conversationId is directly on the conversation object
  if (conversation.conversationId) {
    return conversation.conversationId;
  }

  // Fallback to getting it from the first message if available
  if (conversation.messages.length > 0) {
    return conversation.messages[0].conversationId;
  }

  return undefined;
};

const mapConversationItem = (conversation: ConversationResponse, index: number): ConversationItem => {
  const conversationId = mapConversationId(conversation);
  const latestMessage = conversation.messages[conversation.messages.length - 1];

  return {
    id: conversationId ?? `${conversation.userId}-${conversation.title}-${index}`,
    conversationId,
    userId: conversation.userId,
    title: conversation.title,
    isActive: conversation.isActive,
    messageCount: conversation.messageCount,
    summary: conversation.summary,
    updatedAt: latestMessage?.updatedAt ?? latestMessage?.createdAt,
  };
};

const mapToUiMessage = (message: {
  id: string;
  role: string;
  content: string;
  createdAt?: string;
}): Message => ({
  id: message.id,
  role: message.role?.toLowerCase() === 'assistant' ? 'assistant' : 'user',
  content: message.content,
  timestamp: message.createdAt ? new Date(message.createdAt) : new Date(),
});

const normalizeConversationMessages = (mappedMessages: Message[]): Message[] => {
  if (mappedMessages.length <= 1) {
    return mappedMessages;
  }

  // Keep autogenerated assistant greeting first when present.
  const greetingIndex = mappedMessages.findIndex(
    (message) =>
      message.role === 'assistant' &&
      /little phoenix|how can i help|nice to meet you/i.test(message.content)
  );

  if (greetingIndex <= 0) {
    return mappedMessages;
  }

  const greetingMessage = mappedMessages[greetingIndex];
  const remainingMessages = mappedMessages.filter((_, index) => index !== greetingIndex);
  return [greetingMessage, ...remainingMessages];
};

export const ConversationContext = createContext<ConversationContextType | undefined>(undefined);

export const ConversationProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const { isAuthenticated } = useAuth();
  const [conversations, setConversations] = useState<ConversationItem[]>([]);
  const [activeConversationId, setActiveConversationId] = useState<string | null>(null);
  const [messages, setMessages] = useState<Message[]>([defaultAssistantMessage()]);
  const [isLoadingConversations, setIsLoadingConversations] = useState(false);
  const [isLoadingMessages, setIsLoadingMessages] = useState(false);
  const [isSendingMessage, setIsSendingMessage] = useState(false);
  const [chatError, setChatError] = useState<string | null>(null);
  const isCreatingNewConversationRef = useRef(false);

  const fetchConversations = useCallback(async (): Promise<ConversationItem[]> => {
    console.log('fetchConversations: starting');
    const data = await api.getUserConversations();
    console.log('fetchConversations: received data', { count: data.length });
    const mapped = data
      .map((conversation, index) => mapConversationItem(conversation, index))
      .sort((a, b) => new Date(b.updatedAt ?? 0).getTime() - new Date(a.updatedAt ?? 0).getTime());
    console.log('fetchConversations: mapped conversations', { count: mapped.length, ids: mapped.map(c => c.conversationId) });
    setConversations(mapped);
    return mapped;
  }, []);

  const selectConversation = useCallback(async (conversationId?: string, skipFetch?: boolean) => {
    // Don't fetch messages if explicitly skipped
    if (skipFetch) {
      console.log('selectConversation: skipping fetch', { conversationId });
      setActiveConversationId(conversationId ?? null);
      return;
    }

    console.log('selectConversation: fetching messages', { conversationId });

    try {
      setIsLoadingMessages(true);
      setChatError(null);
      const response = await api.getConversationMessages(conversationId);
      console.log('selectConversation: received messages', { count: response.length });
      
      const mappedMessages = response
        .slice()
        .sort((a, b) => Number(a.order) - Number(b.order))
        .map(mapToUiMessage);

      setActiveConversationId(conversationId ?? (response[0]?.conversationId ?? null));
      setMessages(mappedMessages.length > 0 ? mappedMessages : [defaultAssistantMessage()]);
    } catch (error) {
      console.error('selectConversation: error', error);
      setChatError(error instanceof Error ? error.message : 'Failed to load conversation messages');
    } finally {
      setIsLoadingMessages(false);
    }
  }, []);

  const refreshConversations = useCallback(async () => {
    if (!isAuthenticated) {
      console.log('refreshConversations: not authenticated');
      return;
    }

    try {
      console.log('refreshConversations: starting');
      setIsLoadingConversations(true);
      const mapped = await fetchConversations();
      console.log('refreshConversations: fetched conversations', { count: mapped.length });

      if (mapped.length === 0) {
        console.log('refreshConversations: no conversations');
        setActiveConversationId(null);
        setMessages([defaultAssistantMessage()]);
        return;
      }

      // Skip auto-selection when intentionally creating a new conversation
      if (isCreatingNewConversationRef.current) {
        console.log('refreshConversations: creating new conversation, skipping');
        isCreatingNewConversationRef.current = false;
        return;
      }

      // Try to find and select the active conversation from the backend
      const activeConversation = mapped.find((conversation) => conversation.isActive);
      console.log('refreshConversations: active conversation', { found: !!activeConversation, conversationId: activeConversation?.conversationId });
      
      if (activeConversation && activeConversation.conversationId) {
        console.log('refreshConversations: calling selectConversation with active', { conversationId: activeConversation.conversationId });
        await selectConversation(activeConversation.conversationId, false);
      } else if (mapped[0] && mapped[0].conversationId) {
        // Fallback to first conversation if no active one found
        console.log('refreshConversations: calling selectConversation with first', { conversationId: mapped[0].conversationId });
        await selectConversation(mapped[0].conversationId, false);
      } else {
        console.log('refreshConversations: no valid conversation to select');
      }
    } catch (error) {
      console.error('refreshConversations: error', error);
      setChatError(error instanceof Error ? error.message : 'Failed to load conversation history');
    } finally {
      setIsLoadingConversations(false);
    }
  }, [fetchConversations, isAuthenticated, selectConversation]);

  const startNewConversation = useCallback(() => {
    isCreatingNewConversationRef.current = true;
    setActiveConversationId(null);
    setChatError(null);
    setMessages([defaultAssistantMessage()]);
  }, []);

  const sendMessage = useCallback(
    async (text: string) => {
      const trimmedText = text.trim();
      if (!trimmedText) return;

      const optimisticUserMessage: Message = {
        id: `local-user-${Date.now()}`,
        role: 'user',
        content: trimmedText,
        timestamp: new Date(),
      };

      setMessages((prev) => [...prev, optimisticUserMessage]);
      setIsSendingMessage(true);
      setChatError(null);

      try {
        const isNewConv = !activeConversationId;
        const response = await api.ask(trimmedText, activeConversationId ?? undefined, isNewConv);

        const assistantMessage: Message = {
          id: response.id ?? `local-assistant-${Date.now()}`,
          role: 'assistant',
          content: response.answer,
          timestamp: response.createdAt ? new Date(response.createdAt) : new Date(),
        };

        setMessages((prev) => [...prev, assistantMessage]);
        isCreatingNewConversationRef.current = false;

        if (response.conversationId) {
          setActiveConversationId(response.conversationId);
          await refreshConversations();
          await selectConversation(response.conversationId, false);
        } else {
          await refreshConversations();
        }
      } catch (error) {
        setChatError(error instanceof Error ? error.message : 'Failed to get response');
        isCreatingNewConversationRef.current = false;
      } finally {
        setIsSendingMessage(false);
      }
    },
    [activeConversationId, refreshConversations, selectConversation]
  );

  useEffect(() => {
    if (!isAuthenticated) {
      setConversations([]);
      setActiveConversationId(null);
      setMessages([defaultAssistantMessage()]);
      setChatError(null);
      return;
    }

    refreshConversations();
  }, [isAuthenticated, refreshConversations]);

  const value = useMemo(
    () => ({
      conversations,
      activeConversationId,
      messages,
      isLoadingConversations,
      isLoadingMessages,
      isSendingMessage,
      chatError,
      sendMessage,
      selectConversation,
      startNewConversation,
      refreshConversations,
    }),
    [
      conversations,
      activeConversationId,
      messages,
      isLoadingConversations,
      isLoadingMessages,
      isSendingMessage,
      chatError,
      sendMessage,
      selectConversation,
      startNewConversation,
      refreshConversations,
    ]
  );

  return <ConversationContext.Provider value={value}>{children}</ConversationContext.Provider>;
};
